version: '3.4'

services:
  sut:
    build: ./test
    volumes:
      - ./test:/tests-dir
    depends_on:
      - omnidb
      - lint
      - lint-tests
    links:
      - omnidb
      - lint
      - lint-tests
    command: python3 /tests-dir/test-omnidb.py

  lint:
    image: redcoolbeans/dockerlint
    volumes:
      - ./Dockerfile/:/Dockerfile
    command: -p -f /Dockerfile

  lint-tests:
    image: redcoolbeans/dockerlint
    volumes:
      - ./test/Dockerfile:/Dockerfile
    command: -p -f /Dockerfile

  omnidb:
    build: .
